name: lita-slack

up:
  - ruby:
      version: 2.5.7
  - bundler
  - railgun

commands:
  test:
    desc: Runs the rspec tests against the local redis instance
    run: REDIS_HOST="192.168.64.243" REDIS_PORT=6379 bundle exec rspec
